version: '3.8'

services:
  price_checker:
    build: .
    container_name: pm_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Маппинг всей папки проекта внутрь контейнера
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1